export enum OBJECTIVE_ENUMS {
  LEARNING_OBJECTIVE = "LEARNING_OBJECTIVE",
  CONNECTION_TO_PRIOR_KNOWLEDGE = "CONNECTION_TO_PRIOR_KNOWLEDGE",
  PRIMARY_PRESENTATION_FORM = "PRIMARY_PRESENTATION_FORM",
  EVIDENCE_BASED_STRATEGIES = "EVIDENCE_BASED_STRATEGIES",
  ZOOMING = "ZOOMING",
  POWER_POINT = "POWER_POINT",
}
